import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PageShell } from '../../components/SiteFrame';

const content: Record<string, { no: string; title: string; lead: string; color: string; facts: string[]; sections: { title: string; body: string }[] }> = {
  'glas-na-mladite': { no: '01', title: 'Глас на младите', lead: 'Кога младите луѓе имаат микрофон, ментор и мал буџет, идеите не остануваат на лист хартија.', color: 'coral', facts: ['126 учесници во 2025', '18 ментори', '9 микро-акции'], sections: [{ title: 'Совет од маалото', body: 'Еднаш месечно, 20 млади од три скопски населби се среќаваат со локални луѓе кои носат одлуки. Тие избираат една ствар што може да се промени за 60 дена.' }, { title: 'Од идеја до улица', body: 'Тимовите добиваат материјали, ментор и 15.000 денари за да го направат својот прв прототип: табла со мапа, спортски ден, или мирен агол за учење.' }] },
  'zeleni-maala': { no: '02', title: 'Зелени маала', lead: 'Повеќе зеленило не е украс. Тоа е сенка, место за разговор и подобар ден во градот.', color: 'green', facts: ['420 засадени садници', '11 уредени агли', '86 соседи во акција'], sections: [{ title: 'Мапа на сенка', body: 'Со ученици и постари соседи бележиме каде летото е најжешко и каде недостига место за одмор. Потоа одлучуваме што може реално да се направи.' }, { title: 'Мал парк, голема промена', body: 'Нашата тековна акција во Карпош претвора напуштен агол во мини-градина. Има клупи, дива нане, овошни грмушки и правило: секој што наводнува може да предложи следна идеја.' }] },
  'kultura-na-griza': { no: '03', title: 'Култура на грижа', lead: 'Малите средби создаваат голема сигурност: луѓе што се познаваат полесно си помагаат.', color: 'gold', facts: ['34 соседски средби', '560 споделени оброци', '6 генерации на една маса'], sections: [{ title: 'Соседска маса', body: 'Секој последен четврток во месецот поставуваме долга маса таму каде што има потреба од разговор. Нема агенда, само домашна храна и едно прашање: што ни треба повеќе?' }, { title: 'Вештини што патуваат', body: 'Пензионери учат деца да поправаат велосипеди; средношколци им покажуваат на соседите како да користат онлајн услуги. Знаењето се множи кога се дели.' }] },
  'mal-park': { no: 'АКЦИЈА', title: 'Мал парк, голема промена', lead: 'Напуштен агол зад маркетот во Карпош станува градина, игралиште и место за предах.', color: 'green', facts: ['86 соседи', '72% од целта', 'Сабота · 10:00'], sections: [{ title: 'Што правиме?', body: 'Го расчистуваме просторот, поставуваме две клупи од реупотребено дрво и садиме растенија што издржуваат скопско лето. Планот е направен на три јавни средби.' }, { title: 'Како да помогнеш', body: 'Донеси работни ракавици, една стара саксија или само добра волја. Пријави се преку е-пошта и ќе ти испратиме мапа и список со потребни работи.' }] },
};

export default async function ProgrammeDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const p = content[slug]; if (!p) notFound();
  return <PageShell><section className={`detail-hero ${p.color}`}><p className="eyebrow"><span /> {p.no} · ПРОГРАМА</p><Link className="back-link" href="/programi">← Сите програми</Link><h1>{p.title}</h1><p>{p.lead}</p><div className="detail-orb">{p.no === '01' ? '✳' : p.no === '02' ? '⌁' : '♡'}</div></section><section className="fact-row">{p.facts.map((fact) => <p key={fact}>{fact}</p>)}</section><section className="article-content">{p.sections.map((s) => <article key={s.title}><p className="eyebrow">МОСТАРИ / {p.no}</p><h2>{s.title}</h2><p>{s.body}</p></article>)}<aside><h3>Следен чекор?</h3><p>Ако оваа програма те допира, дојди на следната отворена средба.</p><Link className="button button-dark" href="/vkluci-se">Вклучи се <span>→</span></Link></aside></section><section className="more-links"><Link href="/programi">← Назад кон програми</Link><Link href="/prikazni">Прочитај приказни од маалото →</Link></section></PageShell>;
}
