import Link from 'next/link';
import { notFound } from 'next/navigation';
import { PageShell } from '../../components/SiteFrame';

const stories: Record<string, { tag: string; title: string; lead: string; first: string; quote: string; last: string; colour: string; symbol: string }> = {
  'kino-taftalidze': { tag: 'КУЛТУРА НА ГРИЖА · 02 ЈУЛИ 2026', title: 'Кино под ѕвездите: Тафталиџе си го врати плоштадот', lead: 'Стотина столици, проектор од сосед и едно летно кино што остави луѓе да зборуваат до полноќ.', first: 'Плоштадот кај старата пошта обично се празни веднаш по зајдисонце. Но во петокот таму имаше домашни колачи, 112 метални столици и бело платно растегнато меѓу две дрвја.', quote: '„Не дојдов само за филмот. Дојдов затоа што знаев дека ќе сретнам некого.“', last: 'Следната проекција е веќе договорена. Овој пат програмата ќе ја изберат децата од околните згради.', colour: '#f0997f', symbol: '◒' },
  'mladi-mapa': { tag: 'ГЛАС НА МЛАДИТЕ · 11 АВГУСТ 2026', title: 'Младите направија мапа на местата каде се чувствуваат безбедно', lead: 'Триесет средношколци поминаа низ својот град со телефони, тетратки и многу важни прашања.', first: 'Мапата почна со едно едноставно прашање: каде би го испратил/а помалиот брат или сестра сам/а? Одговорите открија дека осветлувањето, премините и погледот од излозите значат повеќе отколку што изгледа.', quote: '„Ако некој нè праша, имаме конкретен одговор — не само чувство.“', last: 'Предлозите ќе бидат предадени на општината во септември, заедно со фотографии и идеи за мали, брзи поправки.', colour: '#9fc9ab', symbol: '✳' },
};
export default async function Story({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const s = stories[slug]; if (!s) notFound(); return <PageShell><article className="long-story"><Link className="back-link" href="/prikazni">← Сите приказни</Link><p className="eyebrow"><span /> {s.tag}</p><h1>{s.title}</h1><p className="story-lead">{s.lead}</p><div className="article-illustration" style={{ background: s.colour }}><span>{s.symbol}</span><i /><i /><i /></div><div className="story-body"><p>{s.first}</p><blockquote>{s.quote}</blockquote><p>{s.last}</p></div><div className="story-next"><p>Сакаш да бидеш на следната акција?</p><Link className="button button-dark" href="/vkluci-se">Приклучи се <span>→</span></Link></div></article></PageShell>; }
